apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-role
  namespace: demopipelines
rules:
  - apiGroups:
      - ""
      - apps
      - networking.k8s.io
    resources:
      - deployments
      - services
      - secrets
      - ingresses
      - replicasets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]