apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-rolebinding
  namespace: demopipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-role
subjects:
- namespace: demopipelines
  kind: ServiceAccount
  name: demopipeline-sa
