apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-docker-image-task
  namespace: demopipelines
spec:
  workspaces:
    - name: output
  params:
    - name: app_repo
    - name: container_image
    - name: container_tag
    - name: secret-name
  volumes:
    - name: kaniko-secret
      secret:
        secretName: $(params.secret-name) #nameofthedockersecret
        items: 
        - key: .dockerconfigjson
          path: config.json
  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:debug
      workingDir: "/workspace/output/"
      command: [/kaniko/executor]
      args: 
        - --context=./
        - --destination=$(params.container_image):$(params.container_tag)
        - --force
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker/
  